services:
  django:
    build: .
    container_name: barbing_salon_default
    command: gunicorn --bind 0.0.0.0:8000 barbing_salon.wsgi:application
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - pgdb
      - redis


  celery:
    build: .
    command: celery -A barbing_salon.celery worker -l INFO
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - RENDER=${RENDER_URL}
      - CELERY_BROKER=${CELERY_BROKER}
      - CELERY_BACKEND=${CELERY_BACKEND}
    depends_on:
      - django
      - redis
    user: "1000:1000"  # Ensure this user exists in your Dockerfile or create a user with the correct UID and GID

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
