FROM python:3.12

# Set the working directory
WORKDIR /usr/src/app

# Copy application code
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Switch to non-root user
RUN useradd -ms /bin/sh myuser
USER myuser

# Command to run Celery worker
CMD ["celery", "-A", "barbing_salon", "worker", "--loglevel=info"]
