version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn barbing_salon.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    command: celery -A barbing_salon worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    user: "1001:1001"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  redis:
    image: redis:6
    environment:
      - REDIS_URL=${REDIS_URL}

  # create_superuser:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: sh -c "python manage.py migrate && python manage.py createsuperuser --no-input"
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - .env

volumes:
  postgres_data:
