services:
    django:
        build: .
        container_name: barbing_salon_default
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=${DEBUG}
            - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
            - CELERY_BROKER=${CELERY_BROKER}
            - CELERY_BACKEND=${CELERY_BACKEND}
        depends_on:
            - pgdb
            - redis

    celery:
        build: .
        command: celery -A barbing_salon.celery worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=${DEBUG}
            - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
            - RENDER=${RENDER}
            - CELERY_BROKER=${CELERY_BROKER}
            - CELERY_BACKEND=${CELERY_BACKEND}
        depends_on:
            - django
            - redis
        user: "1000:1000" # Replace with a non-root user ID and group ID

    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data/

    redis:
        image: "redis:alpine"

volumes:
    pgdata:
