# Use the official Python image as the base image
FROM python:3.12

# Set the working directory
WORKDIR /usr/src/app

# Copy application code
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Create a group and user
RUN addgroup -S mygroup && adduser -S myuser -G mygroup

# Change ownership of the application files to the non-root user
RUN chown -R myuser:mygroup /usr/src/app

# Switch to non-root user
USER myuser

# Command to run Celery worker
CMD ["celery", "-A", "barbing_salon", "worker", "--loglevel=info"]
