# Generated by Django 5.0.7 on 2024-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, max_length=4, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('stylist', models.CharField(choices=[('Pastor', 'Pastor'), ('Orebiyi', 'Orebiyi'), ('Femi', 'Femi'), ('random', 'Random')], max_length=20)),
                ('service', models.CharField(choices=[('trimming', 'Trimming'), ('haircut', 'Haircut'), ('shaving', 'Shaving')], max_length=20)),
                ('customer_firstname', models.CharField(max_length=200)),
                ('customer_lastname', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('end_time', models.TimeField(null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointment_appointment',
                'unique_together': {('date', 'time', 'stylist')},
            },
        ),
    ]
