# Generated by Django 5.0.7 on 2024-07-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('trimming', 'Trimming'), ('haircut', 'Haircut'), ('shaving', 'Shaving')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.CharField(choices=[('pastor', 'Pastor'), ('orebiyi', 'Orebiyi'), ('femi', 'Femi'), ('random', 'Random')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
    ]
