# Generated by Django 5.0.7 on 2024-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('trimming', 'Trimming'), ('haircut', 'Haircut'), ('shaving', 'Shaving'), ('home_service', 'Home Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Orebiyi', 'Orebiyi'), ('Femi', 'Femi'), ('any', 'Any')], max_length=20),
        ),
    ]
