# Generated by Django 5.0.7 on 2024-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_service_alter_appointment_stylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Orebiyi', 'Orebiyi'), ('Femi', 'Femi'), ('Any', 'Any')], max_length=20),
        ),
    ]
