# Generated by Django 5.0.7 on 2024-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_customer_name_appointment_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Orebiyi', 'Orebiyi'), ('Femi', 'Femi'), ('random', 'Random')], max_length=20),
        ),
    ]
