# Generated by Django 5.0.7 on 2024-08-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_style_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='style_sample',
        ),
    ]
