# Generated by Django 5.0.7 on 2024-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_stylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
