# Generated by Django 5.0.7 on 2024-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
