# Generated by Django 5.0.7 on 2024-08-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
