# Generated by Django 5.0.7 on 2024-07-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appointment_duration_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
