# Generated by Django 5.0.7 on 2024-07-22 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
