# Generated by Django 5.0.7 on 2024-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='style_sample',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
