# Generated by Django 5.0.7 on 2024-07-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_id_alter_appointment_ticket_number'),
    ]

    operations = [
    ]
